#=======================================================================
#@V@:Note: File automatically generated by VIDE - 2.00/10Apr03! (BCC32).
# Generated 15:26:44 10 Jan 2009
# This file regenerated each time you run VIDE, so save under a
#    new name if you hand edit, or it will be overwritten.
#=======================================================================

# Standard defines:
.AUTODEPEND

# Borland C++ tools
IMPLIB	= $(BCCROOT)\bin\Implib
ILINK32	= $(BCCROOT)\bin\ILink32
TLIB	= $(BCCROOT)\bin\TLib
BRC32	= $(BCCROOT)\bin\Brc32
TASM32	= $(BCROOT)\bin\Tasm32
CC  	= $(BCCROOT)\bin\BCC32

BCCROOT	= c:\borland\bcc55

HOMEV	=	
VPATH	=	$(HOMEV)\include
oDir	=	.
Bin	=	.
libDirs	=	-L$(BCCROOT)\lib;$(BCCROOT)\lib\psdk

incDirs	=	-I$(BCCROOT)\include

LD_FLAGS =	-v- -Tpe -aa -c
C_FLAGS	=	-q -O1 -v-\
	-D_WINVER=0x0400\
	-D_WIN32_WINNT=0x0400

SRCS	=\
	resource.rc\
	resource2.rc\
	spritewin.c

EXOBJS	=\
	$(oDir)\resource.res\
	$(oDir)\resource2.res\
	$(oDir)\spritewin.obj

ALLOBJS	=	$(EXOBJS)
BCCJUNK	=	*.il* *.csm *.tds
ALLBIN	=	$(Bin)\spritewin32.exe
ALLTGT	=	$(Bin)\spritewin32.exe

# User defines:

#@# Targets follow ---------------------------------

all:	$(ALLTGT)

objs:	$(ALLOBJS)

cleanobjs:
	rm -f $(ALLOBJS)

cleanbin:
	rm -f $(ALLBIN) $(BCCJUNK)

clean:	cleanobjs cleanbin

cleanall:	cleanobjs cleanbin

#@# User Targets follow ---------------------------------

# BCC32 DEF file: add after = if needed
BCC32DEF =
# BCC32 RT lib: cw32.lib static
BCC32RTLIB = cw32
# BCC32 Startup: c0x32.obj-console, c0w32.obj-winapi
BCC32STARTUP = c0w32.obj

#@# Dependency rules follow -----------------------------

$(Bin)\spritewin32.exe : $(EXOBJS)
  $(ILINK32) @&&|
 $(LD_FLAGS) $(libDirs) +
$(BCC32STARTUP) +
$(oDir)\spritewin.obj
$<,$*
import32.lib +
$(BCC32RTLIB).lib
$(BCC32DEF)
$(oDir)\resource.res+$(oDir)\resource2.res

|
$(oDir)\resource.res : resource.rc
  $(BRC32) -r $(incDirs) -fo$@ resource.rc

$(oDir)\resource2.res : resource2.rc
  $(BRC32) -r $(incDirs) -fo$@ resource2.rc

$(oDir)\spritewin.obj : spritewin.c
  $(CC) -c $(C_FLAGS) $(incDirs) -o$@ spritewin.c

